### ISSUE TITLE
Simple Bypasses

### ISSUE THREAD

**Issue by ossie-git** [koangel/grapeSQLI#1]
Hi, although it appears that grapeSQLI detects some SQL injection patterns, some that are detected by libinjection such as:

`" or ""="`

```
$ ./a.out '" or ""="'
sqli with fingerprint of 's&sos'
```

are not detected.  I'm pretty sure that there are a lot of other patterns that aren't detected as well.  Is there any reason that they aren't detected whereas libinjection detects them?  Thanks

**Comment by koangel** [comment]
maybe you need libinjection database or rule files, libinjection github https://github.com/client9/libinjection
