### ISSUE TITLE
Expanding Tests (libinjection vs grapeSQLI)

### ISSUE THREAD

**Issue by ossie-git** [koangel/grapeSQLI#2]
Due to the issue I found, I decided to compare grapeSQLi with libinjection by throwing a bunch of tests at it.  Using common SQLi lists such as [https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/SQLi/Generic-SQLi.txt](https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/SQLi/Generic-SQLi.txt), I wrote the following, which will print out all the matches when using libinjection:

```c
#include <stdio.h>

#include <string.h>

#include "libinjection.h"

int main() {
  char fingerprint[8];
  size_t slen;
  int issqli;
  FILE * fp;
  char buffer[255];

  fp = fopen("payloads.txt", "r");

  while (fgets(buffer, 255, (FILE * ) fp)) {
    slen = strlen(buffer);

    issqli = libinjection_sqli(buffer, slen, fingerprint);
    if (issqli) {
      printf("%s", buffer);
    }
  }

  fclose(fp);

}
```

I then redirected the matches to a file and added a test to SQLParser_test.go that reads from the file and checks to see if it detects SQLi or not.  The following is the test I added:

```go
func Test_SqlCheckFile(t *testing.T) {
	f, err := os.Open("payloads_sqli.txt")
	if err != nil {
		log.Println("Error opening payloads_sqli.txt file")
	}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		payload := scanner.Text()
		err := SQLInject(payload)
		if err == nil {
			fmt.Printf("%s\n", payload)
			t.Fail()
		}
	}
}
```

Running the above, I came up with the following list of SQL payloads that are detected by libinjection and which are not by grapeSQLI.  This isn't a comprehensive list, but it's a start:

```
||(elt(-3+5,bin(15),ord(10),hex(char(45))))
" or sleep(__TIME__)#
" or benchmark(10000000,MD5(1))#
hi' or 'a'='a
")) or benchmark(10000000,MD5(1))#
hi') or ('a'='a
a' waitfor delay '0:0:10'--
" or pg_sleep(__TIME__)--
" or "a"="a
hi' or 'x'='x';
") or sleep(__TIME__)="
 or 'whatever' in ('whatever')
" or isNULL(1/0) /*
" or 1=1--
");waitfor delay '0:0:__TIME__'--
")) or sleep(__TIME__)="
hi' or 1=1 --
") or pg_sleep(__TIME__)--
anything' OR 'x'='x
") or benchmark(10000000,MD5(1))#
" or 0=0 --
")) or pg_sleep(__TIME__)--
' or 1=1
'; exec master..xp_cmdshell 'ping 172.10.1.255'--
')%20or%20('x'='x
' or 0=0 --
' or 0=0 #
' or 1=1--
' or '1'='1'--
' or 1 --'
' or 1=1 or ''='
' or a=a--
') or ('a'='a
'hi' or 'x'='x';
' or username like '%
' or uname like '%
' or userid like '%
' or uid like '%
' or user like '%
' UNION SELECT
' UNION ALL SELECT
' or ''='
' or 3=3
```

**Comment by koangel** [comment]
First of all, thank you for your use, but grapeSQLI is derived from the C language version of libinjection, which is no longer maintained, because its performance is similar to the performance of CGO in the production environment. You can view the perfect data or rules. C language version, GITHUB: https://github.com/client9/libinjection.
